import type {
  CelebrationAnimationProps,
  DsaSectionTabs,
  FooterProps,
  FooterVariant,
  GamificationBadgeProps,
  MainNavbarProps,
  NavbarDropdownContainerProps,
  NavbarDropdownLink,
  NavbarNavigationConfig,
  NavbarProps,
  NavbarSectionVisibility,
  NavbarVariant,
  NavbarVariantConfig,
  OutlineCardProps,
  QuestionDifficulty,
} from "@tbe/types";

export type {
  CelebrationAnimationProps,
  DsaSectionTabs,
  FooterProps,
  FooterVariant,
  GamificationBadgeProps,
  MainNavbarProps,
  NavbarDropdownContainerProps,
  NavbarDropdownLink,
  NavbarNavigationConfig,
  NavbarProps,
  NavbarSectionVisibility,
  NavbarVariant,
  NavbarVariantConfig,
  OutlineCardProps,
  QuestionDifficulty,
};
