import type {
  AptitudeAnswerFormatType,
  AptitudeCategoryType,
  AptitudeSubCategoryType,
  AptitudeTopicDefinition,
  CertificateType,
  CompanyType,
  DifficultyType,
  DSADifficultyType,
  DSADomainType,
  DSATopicType,
  GoalType,
  InterviewCategoryType,
  LeaderboardType,
  NotificationType,
  PlatformUsageType,
  PriorityType,
  QuestionFrequencyType,
  RoadmapsType,
  SkillsType,
  SubscriptionFeature,
  SubscriptionStatus,
  SubscriptionType,
  UserPointsActionType,
  UserRoleType,
  WorkDomainType,
} from "@/lib/interfaces";

const apiStatusCodes = {
  OKAY: 200,
  RESOURCE_CREATED: 201,
  SUCCESSFUL_WITHOUT_RESPONSE: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  INTERNAL_SERVER_ERROR: 500,
  METHOD_NOT_ALLOWED: 405,
};

const PROJECT_SKILLS: SkillsType[] = [
  "HTML",
  "CSS",
  "JavaScript",
  "React",
  "TypeScript",
  "NodeJS",
  "ExpressJS",
  "MongoDB",
  "NextJS",
  "TailwindCSS",
];

const ROADMAPS: RoadmapsType[] = [
  "Frontend",
  "Backend",
  "Fullstack",
  "Tech",
  "DSA",
];
const INTERVIEW_QUESTION_FREQUENCY: QuestionFrequencyType[] = [
  "Most Asked",
  "Asked Frequently",
  "Asked Sometimes",
];

const DIFFICULTY_LEVEL: DifficultyType[] = [
  "Beginner",
  "Intermediate",
  "Advanced",
];

const CERTIFICATE_TYPE: CertificateType[] = ["WEBINAR", "SHIKSHA"];

const USER_POINTS_ACTION: UserPointsActionType[] = [
  "ENROLL_COURSE",
  "ENROLL_SHEET",
  "ENROLL_PROJECT",
  "COMPLETE_COURSE_CHAPTER",
  "COMPLETE_PROJECT_CHAPTER",
  "COMPLETE_QUESTION",
  "COMPLETE_COURSE_CERTIFICATE",
  "COMPLETE_PROJECT",
  "COMPLETE_INTERVIEW_SHEET",
  "PROFILE_COMPLETION",
  "SOCIAL_SHARE",
  "FEEDBACK_SUBMIT",
  "VIDEO_WATCH_COMPLETE",
  "FIRST_LOGIN",
  "DAILY_VISIT",
  "STREAK",
  "COMPLETE_QUIZ",
  "QUIZ_PERFECT_SCORE",
  "QUIZ_STREAK",
  "REFER",
  "WEBINAR_ATTEND",
  "DOWNLOAD_CERTIFICATE",
  "HELP_COMMUNITY",
  "RECRUITER_ADDED",
  "PREPLOG_CREATED",
];

const NOTIFICATION_TYPE: NotificationType[] = [
  "WEBINAR",
  "SHIKSHA",
  "PROJECT",
  "INTERVIEW PREP",
  "UPDATE",
  "COHORT",
  "PREP YATRA",
  "TECH YATRA",
  "DSA YATRA",
  "RESUME YATRA",
  "TOOLS",
];

const USER_ROLE: UserRoleType[] = [
  "TECH_STUDENT",
  "NON_TECH_STUDENT",
  "WORKING_PROFESSIONAL",
];

const PLATFORM_USAGE: PlatformUsageType[] = [
  "LEARNING_TECH",
  "BUILDING_PROJECTS",
  "INTERVIEW_PREP",
  "JOB_SEARCH",
];

const WORK_DOMAIN: WorkDomainType[] = [
  "MERN Full-stack",
  "Java Full-stack",
  "Python Full-stack",
  "Data Analysis",
  "Machine Learning",
  "AI",
  "App Development",
  "Others",
];

const YOUTUBE_API_PATH = "https://www.googleapis.com/youtube/v3";

const JOB_SKILL_NORMALIZER = [
  {
    label: [
      "react.js",
      "React.js",
      "react",
      "React.JS",
      "reactjs",
      "React JS",
      "reacts js",
    ],
    value: "React.js",
  },
  {
    label: [
      "NodeJS",
      "node.js",
      "nodejs",
      "Node JS",
      "Node JS",
      "node",
      "Node",
    ],
    value: "Node.js",
  },
  {
    label: ["Javascript", "JS", "JavaScript", "javascript", "js", "js."],
    value: "JavaScript",
  },
  {
    label: [
      "spring boot",
      "Spring Boot",
      "Spring",
      "spring",
      "springboot",
      "spring framework",
      "spring mvc",
      "java spring boot",
    ],
    value: "Spring Boot",
  },
  {
    label: [
      "Java",
      "Java 8",
      "Java 11",
      "java",
      "jsp",
      "java fullstack",
      "java8",
      "java frameworks",
    ],
    value: "Java",
  },
  {
    label: ["Python", "python", "py", "python3", "python 3"],
    value: "Python",
  },
  {
    label: ["C++", "c++", "cpp", "C++11", "C++14", "C++17"],
    value: "C++",
  },
  {
    label: ["C#", "c#", "c sharp", "C# .NET", "C# .net"],
    value: "C#",
  },
  {
    label: ["PHP", "php", "laravel", "Laravel", "php laravel"],
    value: "PHP",
  },
  {
    label: ["HTML", "html", "html5", "html 5", "html/css"],
    value: "HTML",
  },
  {
    label: [
      "CSS",
      "css",
      "css3",
      "flexbox",
      "grid",
      "css flexbox",
      "flex",
      "css grid",
    ],
    value: "CSS",
  },
  {
    label: ["MongoDB", "mongodb", "mongo db", "mongo", "Mongo DB"],
    value: "MongoDB",
  },
  {
    label: ["MySQL", "mysql", "sql", "SQL", "sql server", "mysql database"],
    value: "MySQL",
  },
  {
    label: [
      "git",
      "Git",
      "gitlab",
      "github",
      "GitHub",
      "git hub",
      "bitbucket",
      "gitlab",
    ],
    value: "Git",
  },
  {
    label: ["jquery", "JQuery", "jQuery", "jquery.js", "jquery js"],
    value: "JQuery",
  },
  {
    label: ["PostgreSQL", "postgresql", "postgres", "Postgres", "Postgre"],
    value: "PostgreSQL",
  },
  {
    label: ["Oracle", "oracle", "oracle db", "oracle database"],
    value: "Oracle",
  },
  {
    label: [
      "AWS",
      "aws",
      "Amazon Web Services",
      "amazon web services",
      "aws cloud",
      "aws lambda",
      "Azure",
      "azure",
      "azure devops",
      "azure cloud",
      "GCP",
      "gcp",
      "gcp cloud",
      "Google Cloud",
      "google cloud",
      "google gcp",
      "lambda functions",
    ],
    value: "Cloud",
  },
  {
    label: [
      "elasticsearch",
      "ElasticSearch",
      "elasticsearch.js",
      "elasticsearch js",
    ],
    value: "ElasticSearch",
  },
  {
    label: ["jwt", "JWT", "json web token", "json web tokens"],
    value: "JWT",
  },
  {
    label: ["Vue.Js", "vue.js", "VueJS", "Vue", "vuejs", "vue js"],
    value: "Vue.js",
  },
  {
    label: [
      "Angular",
      "angular",
      "AngularJS",
      "angularjs",
      "Angular JS",
      "angular development",
    ],
    value: "Angular",
  },
  {
    label: ["Django", "django", "django rest framework", "django-rest"],
    value: "Django",
  },
  {
    label: ["Flask", "flask", "flask rest api", "flask-rest"],
    value: "Flask",
  },
  {
    label: ["Ruby on Rails", "Ruby", "ruby", "rails", "ruby on rails"],
    value: "Ruby on Rails",
  },
  {
    label: ["Swift", "swift", "swiftui", "swift ui", "swift 5"],
    value: "Swift",
  },
  {
    label: [
      "Kotlin",
      "kotlin",
      "kotlin android",
      "kotlin js",
      "kotlin coroutines",
    ],
    value: "Kotlin",
  },
  {
    label: [
      "data structures",
      "Data Structures",
      "Data Structures and Algorithms",
      "DSA",
      "dsa",
      "algorithms",
      "Data Structures & Algorithms",
      "Data Structures & Algorithms (DSA)",
      "Data Structures and Algorithms (DSA)",
      "Data Structures and Algorithms (DS)",
    ],
    value: "DSA",
  },
  {
    label: [
      "microservices",
      "Microservices",
      "micro services",
      "micro-services",
      "microservices architecture",
    ],
    value: "Microservices",
  },
  {
    label: [
      "docker",
      "Docker",
      "docker container",
      "docker image",
      "container",
    ],
    value: "Docker",
  },
  {
    label: ["ci/cd", "CI/CD", "ci - cd", "ci-cd", "ci cd", "ci cd pipeline"],
    value: "CI/CD",
  },
  {
    label: ["open source", "Open Source", "open-source", "Open-Source"],
    value: "Open Source",
  },
  {
    label: ["typescript", "TypeScript", "typescript.js", "typescript js", "ts"],
    value: "TypeScript",
  },
  {
    label: ["golang", "Golang", "go", "Go", "GoLang", "go lang"],
    value: "Golang",
  },
  {
    label: ["kafka", "Kafka", "kafka stream", "kafka streams"],
    value: "Kafka",
  },
  {
    label: ["system design", "System Design", "system-design", "System-Design"],
    value: "System Design",
  },
  {
    label: ["jenkins", "Jenkins", "jenkins pipeline", "jenkins job"],
    value: "Jenkins",
  },
  {
    label: ["redux", "Redux", "redux.js", "redux js", "redux toolkit"],
    value: "Redux",
  },
  {
    label: [
      "salesforce",
      "Salesforce",
      "sales force",
      "sales force",
      "sales force development",
      "salesforce sales cloud",
    ],
    value: "Salesforce",
  },
  {
    label: ["apache", "Apache", "apache spark", "apache kafka"],
    value: "Apache",
  },
  {
    label: ["ruby on rails", "Ruby on Rails", "ruby on rails", "rails"],
    value: "Ruby on Rails",
  },
  {
    label: [
      "flutter",
      "Flutter",
      "flutter.dev",
      "flutter js",
      "flutter development",
    ],
    value: "Flutter",
  },
  {
    label: ["power bi", "Power BI", "powerbi", "power bi desktop"],
    value: "Power BI",
  },
  {
    label: ["scala", "Scala", "scala.js", "scala js", "scala programming"],
    value: "Scala",
  },
  {
    label: ["pyspark", "PySpark", "python spark", "spark"],
    value: "PySpark",
  },
  {
    label: ["tableau", "Tableau", "tableau public", "tableau server"],
    value: "Tableau",
  },
  {
    label: ["terraform", "Terraform", "terraform.js", "terraform js"],
    value: "Terraform",
  },
  {
    label: ["react native", "React Native", "reactnative", "react native js"],
    value: "React Native",
  },
  {
    label: [
      "cyber security",
      "Cyber Security",
      "cybersecurity",
      "cyber security",
    ],
    value: "Cyber Security",
  },
  {
    label: [
      "functional testing",
      "Functional Testing",
      "api testing",
      "regression testing",
      "software testing",
      "unit testing",
      "performance testing",
      "manual testing",
      "system testing",
      "security testing",
      "development testing",
      "load testing",
      "mobile testing",
      "automation testing",
    ],
    value: "Testing",
  },
  {
    label: ["grafana", "Grafana", "grafana dashboard", "grafana monitoring"],
    value: "Grafana",
  },
  {
    label: ["laravel", "Laravel", "laravel php"],
    value: "Laravel",
  },
  {
    label: ["numpy", "NumPy", "numpy.js", "numpy js"],
    value: "NumPy",
  },
  {
    label: ["sqlite", "SQLite", "sqlite3", "sqlite database"],
    value: "SQLite",
  },
  {
    label: ["Swift", "SwiftUI", "swiftui", "swift ui", "swift 5"],
    value: "SwiftUI",
  },
  {
    label: ["hadoop", "Hadoop", "hadoop ecosystem", "hadoop cluster"],
    value: "Hadoop",
  },
  {
    label: ["excel", "Excel", "excel vba", "excel macros"],
    value: "Excel",
  },
  {
    label: ["tableau", "Tableau", "tableau public", "tableau server"],
    value: "Tableau",
  },
  {
    label: ["generative ai", "Generative AI", "GenerativeAI", "generative-ai"],
    value: "Generative AI",
  },
  {
    label: ["graphql", "GraphQL", "graphql.js", "graphql js"],
    value: "GraphQL",
  },
  {
    label: ["tensorflow", "TensorFlow", "tensor flow", "tensorflow.js"],
    value: "TensorFlow",
  },
  {
    label: [
      "nlp",
      "NLP",
      "natural language processing",
      "Natural Language Processing",
    ],
    value: "NLP",
  },
  {
    label: ["pytorch", "PyTorch", "Pytorch", "torch", "torch.js"],
    value: "PyTorch",
  },
  {
    label: ["redis", "Redis", "redis db", "redis database"],
    value: "Redis",
  },
  {
    label: ["nextjs", "Next.js", "Next JS", "next js", "next.js"],
    value: "Next.js",
  },
  {
    label: ["figma", "Figma", "figma design", "figma design system"],
    value: "Figma",
  },
  {
    label: ["matlab", "MATLAB", "matlab programming", "matlab script"],
    value: "MATLAB",
  },
  {
    label: ["asp.net core", "ASP.NET Core", "asp.net", "ASP.NET"],
    value: "ASP.NET",
  },
  {
    label: ["ui/ux", "UI/UX", "ui/ux design", "UI/UX Design", "ui ux", "ui"],
    value: "UI/UX",
  },
  {
    label: ["cassandra", "Cassandra", "cassandra db", "cassandra database"],
    value: "Cassandra",
  },
  {
    label: [
      "expressjs",
      "expresjs",
      "ExpressJS",
      "express js",
      "express.js",
      "express",
      "express.js",
    ],
    value: "ExpressJS",
  },
  {
    label: ["fastapi", "FastAPI", "fast api", "fastapi.js", "fastapi js"],
    value: "FastAPI",
  },
  {
    label: ["scikit-learn", "Scikit-learn", "scikit learn", "scikit-learn.js"],
    value: "Scikit-learn",
  },
  {
    label: ["dart", "Dart", "dart.js", "dart js"],
    value: "Dart",
  },
  {
    label: ["dynamo db", "DynamoDB", "dynamodb", "dynamo db"],
    value: "DynamoDB",
  },
  {
    label: ["kubernetes", "Kubernetes", "k8s", "k8s cluster"],
    value: "Kubernetes",
  },
  {
    label: ["nosql", "NoSQL", "nosql database", "nosql db"],
    value: "NoSQL",
  },
  {
    label: [
      "linux",
      "Linux",
      "linux server",
      "linux os",
      "linux kernel",
      "redhat linux",
      "embedded linux",
      "linux administration",
    ],
    value: "Linux",
  },
];

const JOB_LOCATION_NORMALIZER = [
  {
    label: ["Bengaluru", "Bangalore"],
    value: "Bangalore",
  },
  {
    label: ["Delhi NCR", "Delhi", "New Delhi", "Delhi / NCR"],
    value: "Delhi",
  },
  {
    label: ["Bombay", "Mumbai", "Mumbai (All Areas)"],
    value: "Mumbai",
  },
  {
    label: ["Hybrid - Hyderabad"],
    value: "Hyderabad",
  },
  {
    label: ["Remote", "Work From Home"],
    value: "Remote",
  },
];

const JOB_DOMAIN_NORMALIZER = [
  {
    label: [
      "Full Stack Developer",
      "Full Stack Development",
      "Full-Stack Development",
      "Full-Stack Developer",
      "Fullstack",
      "Full Stack",
      "Full Stack Developer (Frontend)",
      "Full Stack Developer (Backend)",
      "Full Stack Developer (Mobile)",
      "Full Stack Developer (Web)",
      "Full Stack Developer (Web Development)",
      "Java Full Stack Developer",
      "Full Stack Application Development",
    ],
    value: "Full Stack Development",
  },
  {
    label: ["Backend Developer", "Backend Development", "Backend", "Back End"],
    value: "Backend Development",
  },
  {
    label: [
      "Frontend Developer",
      "Frontend Development",
      "Frontend",
      "Front End",
      "Front-End",
    ],
    value: "Frontend Development",
  },
  {
    label: [
      "Software Engineer",
      "Software Development",
      "Software Engineering",
      "Senior Software Engineer",
      "Software Development Engineer",
      "Other Software Development",
      "Computer science",
      "Debugging",
    ],
    value: "Software Development",
  },
  {
    label: ["Data Analyst", "Data Analytics", "Data Analysis"],
    value: "Data Analysis",
  },
  {
    label: [
      "Data Science",
      "Data Scientist",
      "Data Science / Machine Learning",
      "Data Science / AI",
      "Data Science / Data Analyst",
      "Data Science / Data Engineer",
      "Data Science / Data Science",
      "Data Science / Data Science / Machine Learning",
    ],
    value: "Data Science",
  },
  {
    label: ["DevOps Engineer", "DevOps", "DevOps Development"],
    value: "DevOps",
  },
  {
    label: [
      "Mobile Development",
      "Mobile Developer",
      "Android Developer",
      "Full Stack Developer (Mobile)",
      "Mobile App Development",
      "Mobile Application Development",
      "Mobile Application Developer",
      "Mobile App Developer",
      "Flutter Developer",
    ],
    value: "Mobile Development",
  },

  {
    label: ["Java Developer", "Java Development", "Java", "Java 8", "Java 11"],
    value: "Java Development",
  },
  {
    label: [
      "QA / SDET",
      "Quality Assurance",
      "QA Engineer",
      "Quality Engineer",
      "Quality Analyst",
      "Quality Assurance Engineer",
      "Quality Assurance Analyst",
      "Quality Analyst Engineer",
      "Quality Assurance Tester",
      "Quality Assurance Automation Engineer",
      "Quality Assurance Automation Tester",
      "Quality Assurance Automation Analyst",
    ],
    value: "QA Engineering",
  },
  {
    label: ["Web Development", "Web Developer", "Web Development (Frontend)"],
    value: "Web Development",
  },
  {
    label: ["Cloud Computing", "Cloud Engineer", "Cloud Developer", "Cloud"],
    value: "Cloud Computing",
  },
  {
    label: ["Machine Learning", "ML", "Data Science / Machine Learning"],
    value: "Machine Learning",
  },
];

const JOB_DOMAIN_MAPPER = [
  {
    skills: [
      "React.js",
      "Frontend",
      "HTML",
      "CSS",
      "Vue.js",
      "Angular",
      "Tailwind",
      "Bootstrap",
    ],
    domain: ["Frontend Development"],
  },
  {
    skills: [
      "NodeJS",
      "Spring Boot",
      "PHP",
      "MongoDB",
      "MySQL",
      "PostgreSQL",
      "Django",
      "Ruby on Rails",
      "Flask",
      "ExpressJS",
    ],
    domain: ["Backend Development"],
  },
  {
    skills: ["Java", "Java 8", "Java 11"],
    domain: ["Java Development", "Backend Development"],
  },
  {
    skills: ["Python", "Django", "Flask"],
    domain: ["Python Development", "Backend Development"],
  },
  {
    skills: ["Swift", "Kotlin"],
    domain: ["Mobile Development"],
  },
  {
    skills: [
      "Software Engineer",
      "Software Development",
      "Software Engineering",
      "Senior Software Engineer",
      "Software Development Engineer",
      "Other Software Development",
      "Computer science",
      "Debugging",
    ],
    domain: ["Software Development"],
  },
  {
    skills: ["DevOps", "Cloud Computing", "Oracle", "AWS", "Azure", "GCP"],
    domain: ["DevOps"],
  },
  {
    skills: ["Data Science", "Machine Learning", "Data Analysis"],
    domain: ["Data Science"],
  },
  {
    skills: ["QA / SDET", "Quality Assurance", "QA Engineer"],
    domain: ["QA Engineering"],
  },
];

const SKILL_BLACKLIST = [
  "frontend",
  "backend",
  "coding",
  "front",
  "senior",
  "manager",
  "software",
  "development",
  "engineering",
  "dev",
  "tech",
  "developer",
  "programming",
  "agile",
  "automation",
  "debugging",
  "computer science",
  "troubleshooting",
  "linux",
  "analytical",
  "project management",
  "software development",
  "web technologies",
  "application development",
  "networking",
  "architecture",
  "sap",
  "management",
  "hibernate",
  "web development",
  "version control",
  "web services",
  ".net",
  "cloud",
  "xml",
  "machine learning",
  "rest",
  "c",
  "manager technology",
  "json",
  "continuous integration",
  "devops",
  "consulting",
  "scrum",
  "android",
  "selenium",
  "kubernetes",
  "automation testing",
  "software development life cycle",
  "software design",
  "mvc",
  "unix",
  "wordpress",
  "performance tuning",
  "microsoft azure",
  "healthcare",
  "information technology",
  "software engineering",
  "nosql",
  "test cases",
  "windows",
  "jira",
  "microsoft",
  "manager quality assurance",
  "product management",
  "core java",
  "data analysis",
  "full stack",
  "bootstrap",
  "analytics",
  "api",
  "ios",
  "erp",
  "social media",
  "maven",
  "monitoring",
  "data modeling",
  "j2ee",
  "sdlc",
  "design",
  "technical support",
  "dbms",
  ".net core",
  "data management",
  "rdbms",
  "customer service",
  "database design",
  "application",
  "testing",
  "deployment",
  "information security",
  "sales",
  "web designing",
  "operations",
  "plsql",
  "artificial intelligence",
  "cloud computing",
  "ajax",
  "mobile applications",
  "cms",
  "technical",
  "shell scripting",
  "ms sql",
  "agile methodology",
  "testing tools",
  "team management",
  "database",
  "boot",
  "http",
  "ui development",
  "soa",
  "risk management",
  "continuous improvement",
  "workflow",
  "interpersonal skills",
  "root cause analysis",
  "change management",
  "java development",
  "administration",
  "configuration management",
  "architectural design",
  "usage",
  "perl",
  "system architecture",
  "multithreading",
  "etl",
  "business analysis",
  "oops",
  "analytical skills",
  "communication skills",
  "web application",
  "training",
  "data",
  "servicenow",
  "scalability",
  "distribution system",
  "technical leadership",
  "seo",
  "server",
  "production support",
  "entity framework",
  "dns",
  "data warehousing",
  "san",
  "ui",
  "network security",
  "stack",
  "data processing",
  "supply chain",
  "soc",
  "stored procedures",
  "photoshop",
  "finance",
  "incident management",
  "design patterns",
  "pdf",
  "mobile development",
  "mobile application development",
  "sap abap",
  "user interface designing",
  "product design",
  "powershell",
  "integration testing",
  "active directory",
  "web api",
  "adobe",
  "vmware",
  "tdd",
  "infrastructure",
  "agile development",
  "design development",
  "digital marketing",
  "data migration",
  "it services",
  "test scripts",
  "customer support",
  "sap hana",
  "graphics",
  "research",
  "business development",
  "core",
  "end",
  "big data",
  "orchestration",
  "application support",
  "fullstack development",
  "illustrator",
  "compliance",
  "object oriented design",
  "data quality",
  "business intelligence",
  "jdbc",
  "eclipse",
  "e-commerce",
  "side",
  "application design",
  "rest api",
  "frontend development",
  "integration",
  "ux",
  "enterprise applications",
  "data engineering",
  "simulation",
  "internship",
  "database management",
  "mis",
  "crm",
  "sql queries",
  "hp data protector",
  "asp.net mvc",
  "visual studio",
  "android sdk",
  "middleware",
  "android application development",
  "test planning",
  "business process",
  "mvvm",
  "product engineering",
  "financial services",
  "database administration",
  "code",
  "procurement",
  "cad",
  "drupal",
  "apex",
  "system integration",
  "hiring",
  "cloud services",
  "db2",
  "prototype",
  "focus",
  "wcf",
  "sdk",
  "php development",
  "quality assurance",
  "hive",
  "telecom",
  "test driven development",
  "tools",
  "health insurance",
  "dom",
  "process improvement",
  "recruitment",
  "linq",
  "itil",
  "ansible",
  "operational excellence",
  "disaster recovery",
  "scheduling",
  "configuration",
  "sr",
  "snowflake",
  "time management",
  "saas",
  "automation framework",
  "informatica",
  "firmware",
  "billing",
  "cloud security",
  "data analytics",
  "hardware",
  "scripting",
  "schema",
  "iso",
  "rtos",
  "switching",
  "career development",
  "packaging",
  "service management",
  "software solutions",
  "accounting",
  "presales",
  "autocad",
  "itsm",
  "mentor",
  "object oriented programming",
  "qa",
  "access management",
  "dot",
  "abap",
  "developing",
  "data security",
  "api integration",
  "soap",
  "architect",
  "security",
  "presentation skills",
  "asset management",
  "assurance",
  "tomcat",
  "microsoft dynamics",
  "content management",
  "documentation",
  "ios development",
  "application security",
  "application software",
  "problem management",
  "computer vision",
  "data science",
  "android studio",
  "cs",
  "python development",
  "agile scrum",
  "production",
  "solution architecture",
  "product quality",
  "performance optimization",
  "visualforce",
  "data visualization",
  "performance management",
  "technical lead",
  "hr",
  "tcp",
  "diversity and inclusion",
  "operating systems",
  "jms",
  "ethernet",
  "publishing",
  "program",
  "technology",
  "customer experience",
  "software quality",
  "io",
  "cobol",
  "basic",
  "backend development",
  "ssis",
  "stakeholder management",
  "mobile",
  "vpn",
  "web application development",
  "core php",
  "project delivery",
  "splunk",
  "ssrs",
  "framework",
  "cd",
  "solution design",
  "enterprise architecture",
  "wellness",
  "sql database",
  "system administration",
  "sap abap development",
  "payroll",
  "sharepoint",
  "jpa",
  "uml",
  "investment banking",
  "english",
  "banking",
  "appium",
  "it support",
  "automotive",
  "spring mvc",
  "wan",
  "desktop support",
  "incharge",
  "cisco",
  "wpf",
  "sdet",
  "virtualization",
  "network engineering",
  "project planning",
  "interaction design",
  "embedded systems",
  "jcl",
  "azure data factory",
  "weblogic",
  "animation",
  "google analytics",
  "statistics",
  "application programming",
  "mca",
  "ms office",
  "jboss",
  "pmp",
  "iphone",
  "process",
  "sap fiori",
  "business analyst",
  "sap s hana",
  "assembly language",
  "junit",
  "restful api",
  "software development methodologies",
  "software architecture",
  "data governance",
  "leadership",
  "embedded c",
  "test management",
  "web",
  "budgeting",
  "release management",
  "struts",
  "ado.net",
  "ticketing",
  "routing",
  "bpo",
  "lan",
  "infrastructure management",
  "data validation",
  "iis",
  "functional",
  "analysis",
  "problem solving",
  "process automation",
  "wireless",
  "talent acquisition",
  "semiconductor",
  "cvs",
  "siem",
  "joomla",
  "lead generation",
  "technical design",
  "marketing",
  "cucumber",
  "gaming",
  "medical insurance",
  "metadata",
  "ldap",
  "mern stack",
  "confluence",
  "native",
  "cakephp",
  "instrumentation",
  "machine learning algorithms",
  "plm",
  "relationship management",
  "usb",
  "firewall",
  "workday",
  "java spring boot",
  "it",
  "aws cloud",
  "ux design",
  "paas",
  "serv",
  "graphic designing",
  "test execution",
  "xslt",
  "market research",
  "deep learning",
  "memory management",
  "svn",
  "application architecture",
  "ccna",
  "staffing",
  "vb.net",
  "quality standards",
  "technical architecture",
  "data integration",
  "digital transformation",
  "pharma",
  "business strategy",
  "accounts payable",
  "project development",
  "system",
  "data mining",
  "risk assessment",
  "jmeter",
  "product development",
  "aerospace",
  "electronics",
  "telesales",
  "query",
  "sap sd",
  "load balancing",
  "automation tools",
  "accounts receivable",
  "test strategy",
  "it operations",
  "owasp",
  "software quality assurance",
  "query optimization",
  "azure databricks",
  "cics",
  "com",
  "technology management",
  "rest assured",
  "engineering management",
  "operations management",
  "FastAPI",
  "sas",
  "user research",
  "tool design",
  "technology solutions",
  "manual",
  "back office",
  "iso 27001",
  "quality",
  "wordpress cms",
  "it infrastructure",
  "ms dynamics crm",
  "data collection",
  "program management",
  "networking protocols",
  "ssl",
  "desktop",
  "cloud technologies",
  "order management",
  "databricks",
  "technical documentation",
  "bi",
  "retail",
  "business solutions",
  "sfdc",
  "architecting",
  "html;javascript",
  "data integrity",
  "data munging",
  "verilog",
  "powerapps",
  "bfsi",
  "DynamoDB",
  "business transformation",
  "salesforce lightning",
  "odata",
  "vb",
  "technical analysis",
  "iam",
  "pega",
  "servicenow development",
  "system engineering",
  "oracle sql",
  "bigquery",
  "communication protocols",
  "service desk",
  "managed services",
  "scm",
  "process design",
  "professional",
  "asic",
  "asp",
  "account management",
  "manager quality control",
  "gap analysis",
  "life sciences",
  "hrsd",
  "hardware design",
  "writing",
  "team",
  "nunit",
  "remediation",
  "technical writing",
  "equity",
  "six sigma",
  "restful apis",
  "interfaces",
  "integration php",
  "business executive",
  "mainframes",
  "llms",
  "java j2ee developer",
  "mean stack",
  "openshift",
  "sapui5",
  "forecasting",
  "business rules",
  "management systems",
  "vsam",
  "sap mm",
  "design engineering",
  "cmdb",
  "microsoft windows",
  "data bricks",
  "system verilog",
  "user acceptance testing",
  "project",
  "sap fico",
  "test engineering",
  "rpa",
  "system software",
  "supply chain management",
  "electrical engineering",
  "data architecture",
  "xhtml",
  "bdd",
  "fresher",
  "data services",
  "power automate",
  "qa automation",
  "test scenarios",
  "ms azure",
  "installation",
  "bgp",
  "technical product configuration",
  "conceptualization",
  "hardware engineering",
  "team leading",
  "lwc",
  "spi",
  "xcode",
  "hardware networking",
  "linux kernel",
  "pandas",
  "reporting",
  "hipaa",
  "it recruitment",
  "cold calling",
  "issue resolution",
  "sailpoint",
  "service delivery",
  "triggers",
  "cypress",
  "sql development",
  "mern",
  "development manager",
  "security operations",
  "engineering services",
  "pan",
  "power platform",
  "bash",
  "b2c sales",
  "fpga",
  "relational databases",
  "mvc framework",
  "vulnerability",
  "wireframing",
  "analog",
  "monitoring tools",
  "codeigniter",
  "playwright",
  "aem",
  "b2b sales",
  "ooad",
  "translation",
  "adobe creative suite",
  "control system",
  "network administration",
  "modeling",
  "microsoft technologies",
  "ml",
  "edi",
  "adobe xd",
  "contract management",
  "plugins",
  "senior analyst",
  "ups",
  "strategic planning",
  "postman",
  "database creation",
  "high level design",
  "os installation",
  "performance",
  "customer satisfaction",
  "sms",
  "silicon",
  "saps",
  "planning",
  "design principles",
  "sensors",
  "oracle dba",
  "wealth management",
  "french",
  "mechanical",
  "engineering design",
  "airflow",
  "cloud infrastructure",
  "reconciliation",
  "level",
  "relationship",
  "bluetooth",
  "Grafana",
  "data dictionary",
  "sap fi",
  "genesys purecloud",
  "hcm",
  "security compliance",
  "website",
  "devops deployment",
  "image processing",
  "physical design",
  "mvc architecture",
  "redhat linux",
  "voip",
  "lead software",
  "b2b",
  "customer engagement",
  "software development engineer ii",
  "outbound",
  "nginx",
  "data privacy",
  "java developer",
  "gis",
  "api gateway",
  "psd",
  "vulnerability assessment",
  "warehouse",
  "test case execution",
  "fico",
  "saml",
  "net fullstack",
  "Scikit-learn",
  "soap services",
  "email",
  "wordpress development",
  "dreamweaver",
  "auditing",
  "vulnerability management",
  "vhdl",
  "cloud platforms",
  "3d",
  "telecommunication",
  "diagnostics",
  "patch management",
  "prometheus",
  "s3",
  "t-sql",
  "inside sales",
  "real time operating systems",
  "database testing",
  "r",
  "symfony",
  "educational sales",
  "claims",
  "computer",
  "sap cloud platform",
  "dhcp",
  "sap basis",
  "outlook configuration",
  "rest api development",
  "techno functional",
  "ip",
  "visual design",
  "non voice process",
  "helpdesk",
  "inbound sales",
  "mechanical engineering",
  "full stack developer",
  "sap implementation",
  "min",
  "sap basis administration",
  "analyzing information",
  "ticketing tools",
  "gsm",
  "iot",
  "eigrp",
  "fabrication",
  "pcie",
  "client interaction",
  "operational support",
  "soql",
  "end user",
  "team handling",
  "mining",
  "student counseling",
  "visual basic",
  "languages",
  "rabbitmq",
  "net mvc",
  "elastic search",
  "e-learning",
  "financial planning",
  "embedded linux",
  "ftp",
  "design review",
  "windows os",
  "plc",
  "amazon redshift",
  "mathematics",
  "windows server",
  "new product development",
  "etl process",
  "relationship building",
  "code review",
  "catia",
  "electricals",
  "cloud architecture",
  "subject matter expert",
  "enterprise",
  "individual contributor",
  "cisa",
  "sip",
  "teaching",
  "master data management",
  "testng",
  "oauth",
  "l2",
  "software installation",
  "firebase",
  "ai",
  "vendor management",
  "api management",
  "NumPy",
  "service level",
  "scripting languages",
  "ansys",
  "itom",
  "mpls",
  "it management",
  "investment management",
  "neural networks",
  "resource management",
  "delivery",
  "dotnet development",
  "itil framework",
  "software validation",
  "thermal",
  "software engineer ii",
  "software engineer",
  "email marketing",
  "manager program management",
  "it security",
  "digital design",
  "jtag",
  "commerce",
  "channel sales",
  "distribution",
  "windows installation",
  "screening",
  "google",
  "rca",
  "ppc",
  "machine",
  "it helpdesk",
  "service cloud",
  "costing",
  "product support",
  "social media marketing",
  "sez",
  "aws iam",
  "rf",
  "apis",
  "load runner",
  "supervision",
  "dot net",
  "togaf",
  "adobe forms",
  "network support",
  "sccm",
  "websphere",
  "l1",
  "macros",
  "simulink",
  "migration",
  "embedded software",
  "qa testing",
  "penetration testing",
  "cloud platform",
  "typing",
  "ubuntu",
  "unix shell scripting",
  "management consulting",
  "front office",
  "corporate",
  "unit",
  "prototyping",
  "apache tomcat",
  "workday functional",
  "hospitality",
  "visio",
  "voice process",
  "digital",
  "report generation",
  "business process management",
  "azure data lake",
  "site reliability engineering",
  "computer hardware",
  "objective c",
  "it service desk",
  "servicenow it service management",
  "event management",
  "core data",
  "amazon connect",
  "linux administration",
  "software services",
  "payment processing",
  "ab initio",
  "customization",
  "team building",
  "mlops",
  "sap module",
  "hindi",
  "socket programming",
  "bidding",
  "test design",
  "usability testing",
  "process optimization",
  "vlsi",
  "agile methodologies",
  "distributed systems",
  "dft",
  "application testing",
  "network infrastructure",
  "network operations",
  "customer relationship",
  "glue",
  "azure functions",
  "data entry",
  "mobile app",
  "uvm",
  "cism",
  "winforms",
  "sourcing",
  "content writing",
  "lambda functions",
  "autosar",
  "robotics",
  "api automation",
  "calling",
  "service desk management",
  "microsoft dynamics crm technical",
  "lightning",
  "lms",
  "oracle cloud",
  "business services",
  "rxjs",
  "remote support",
  "cost",
  "rfp",
  "automation engineering",
  "genetics",
  "storage",
  "advertising",
  "tds",
  "cpq",
  "security assessment",
  "oracle fusion",
  "android development",
  "life cycle",
  "process compliance",
  "snmp",
  "protocols",
  "resource allocation",
  "network troubleshooting",
  "solid",
  "financial reporting",
  "remote",
  "grc",
  "llm",
  "uat",
  "defect tracking",
  "shopify",
  "recovery",
  "mdm",
  "java script",
  "marketing campaigns",
  "circuit designing",
  "zend",
  "microcontroller",
  "security management",
  "sre",
  "etl testing",
  "php developer",
  "sap upgrade",
  "data modelling",
  "desktop engineering",
  "renewable energy",
  "fixed income",
  "wifi",
  "cloud applications",
  "german",
  "construction",
  "sso",
  "ruby rails",
  "cmmi",
  "data mapping",
  "software configuration management",
  "web analytics",
  "outsourcing",
  "training and development",
  "aiml",
  "cgi",
  "endpoint security",
  "pl/sql",
  "inventory management",
  "full stack development",
  "emc",
  "purchase",
  "teradata",
  "waterfall",
  "mule esb",
  "studio",
  "due diligence",
  "configuring",
  "erp implementation",
  "guidewire",
  "net development",
  "medical devices",
  "legal",
  "jwt",
  "pytest",
  "business analytics",
  "business development executive",
  "emi",
  "nosql databases",
  "bdc",
  "payments",
  "control",
  "shaping",
  "printing",
  "workday integration",
  "selenium webdriver",
  "quality assurance engineering",
  "cash management",
  "quality engineering",
  "abap programming",
  "professional services",
  "software programming",
  "solution architect",
  "javas",
  "tfs",
  "server management",
  "science",
  "hardware troubleshooting",
  "dynatrace",
  "emerging technologies",
  "financial analysis",
  "test case design",
  "be",
  "sem",
  "digital media",
  "uipath",
  "chat process",
  "datastage",
  "implementation",
  "it operations management",
  "3d modeling",
  "bpo non voice",
  "mobile apps testing",
  "progress 4gl",
  "assistant vice president",
  "ci/cd pipelines",
  "architects",
  "verbal communication",
  "ecs",
  "aws devops",
  "sap cloud",
  "lex chatbots",
  "api development",
  "international call center",
  "dsp",
  "hardware support",
  "performance engineering",
  "engineering manager",
  "magento",
  "trade",
  "orm",
  "olap",
  "japanese",
  "azure active directory",
  "product life cycle",
  "pega prpc",
  "technical architect",
  "sta",
  "employee engagement",
  "sap security",
  "sass",
  "it asset management",
  "intelligence",
  "time",
  "device drivers",
  "power electronics",
  "warehouse management",
  "identity access management",
  "revenue generation",
  "lld",
  "insurance",
  "vendor",
  "principal",
  "client",
  "industrial sales",
  "cosmos",
  "spring security",
  "business analysts",
  "sybase",
  "mdg",
  "drives",
  "php mysql",
  "selenium testing",
  "payment gateways",
  "tibco",
  "lan troubleshooting",
  "market data",
  "contracts",
  "dynamic",
  "ccnp",
  ".net framework",
  "csr",
  "enterprise software",
  "pl-sql",
  "cyber",
  "cloud integration",
  "intern",
  "electrical design",
  "regulatory",
  "project life cycle",
  "python framework",
  "gen ai",
  "loans",
  "engineer ii",
  "oracle e-business suite",
  "corel draw",
  "corporate sales",
  "testing methodologies",
  "mulesoft",
  "sap netweaver",
  "taxation",
  "core java development",
  "knowledge management",
  "cyberark",
  "hvac",
  "boomi",
  "us healthcare",
  "delivery management",
  "social networking",
  "rest apis",
  "mockito",
  "cryptography",
  "tcp/ip",
  "firmware development",
  "dotnet",
  "sap mdg",
  "security engineering",
  "scada",
  "database development",
  "kernel",
  "rust",
  "mq",
  "aws glue",
  "sales process",
  "video editing",
  "sap integration",
  "sap erp",
  "leadership development",
  "intellij",
  "direct marketing",
  "quality control",
  "software troubleshooting",
  "as400",
  "oop",
  "office",
  "core java programming",
  "l3",
  "android application",
  "server administration",
  "oracle apps technical",
  "app development",
  "appian",
  "maintenance",
  "ngrx",
  "informatica powercenter",
  "talent management",
  "javascript frameworks",
  "head business development",
  "concept design",
  "online marketing",
  "springboot java",
  "design verification",
  "financial accounting",
  "oracle apex",
  "desk",
  "asset",
  "sap ecc",
  "technical recruitment",
  "asp.net core mvc",
  "solaris",
  "computer operating",
  "powershell scripting",
  "software implementation",
  "linux system administration",
  "mobile application testing",
  "data pipeline",
  "product lifecycle management",
  "antivirus",
  "development lead",
  "investigation",
  "amazon ec2",
  "webpack",
  "web application testing",
  "solution architecting",
  "information management",
  "front end design",
  "qos",
  "tosca",
  "pcb designing",
  "logistics",
  "webdynpro",
  "sap bw",
  "pci dss",
  "isms",
  "tcl",
  "customer care",
  "aix",
  "functional design",
  "mean",
  "system performance",
  "sharepoint development",
  "rds",
  "peoplesoft",
  "devsecops",
  "workday core hcm",
  "product innovation",
  "business continuity management",
  "module development",
  "siebel",
  "process control",
  "service",
  "support services",
  "japanese language",
  "rest api integration",
  "manufacturing",
  "rest api services",
  "system programming",
  "assistance",
  "software sales",
  "kanban",
  "robot framework",
  "selection process",
  "code versioning tools",
  "database security",
  "international voice process",
  "nestjs",
  "rpg",
  "nas",
  "spring batch",
  "servicing",
  "mentoring",
  "itil processes",
  "non it recruitment",
  "java selenium",
  "rhel",
  "continuous deployment",
  "mobile technology",
  "business communication",
  "campaign management",
  "technology consulting",
  "control-m",
  "dynamics",
  "sap master data governance",
  "licensing",
  "access control",
  "ios app",
  "software developer",
  "advocate",
  "rtl",
  "oracle forms",
  "salesforce platform",
  "network design",
  "test automation",
  "hmi",
  "opengl",
  "pipeline",
  "embedded",
  "java frameworks",
  "business administration",
  "end to end recruitment",
  "sap ewm",
  "laptop support",
  "ivr",
  "typing speed",
  "software support",
  "salesforce crm",
  "salesforce integration",
  "internet marketing",
  "automation anywhere",
  "arm",
  "it infrastructure management",
  "hana db",
  "hybris",
  "qt",
  "game development",
  "chef",
  "case",
  "cissp",
  "java architecture",
  "soap ui",
  "gen",
  "equipment",
  "it business resilience",
  "application engineering",
  "azure synapse",
  "genai",
  "voice support",
  "django framework",
  "redhat",
  "css/css3",
  "cognos",
  "jee",
  "sap presales",
  "tally",
  "synthesis",
  "nexus",
  "abap development",
  "ui automation",
  "okta",
  "ricef",
  "vlan",
  "network management",
  "mobile phones",
  "system analysis",
  "ecc",
  "written communication",
  "printer support",
  "oic",
  "blended process",
  "sql azure",
  "soc verification",
  "business applications",
  "embedded software development",
  "non voice",
  "conflict resolution",
  "windows server administration",
  "jest",
  "ssas",
  "field sales",
  "solid works",
  "eks",
  "media",
  "subversion",
  "talend",
  "transition",
  "elk",
  "mysql database",
  "gcp cloud",
  "elasticsearch",
  "sitecore",
  "nagios",
  "freelancing",
  "work from home",
  "telecalling",
  "activemq",
  "client management",
  "internet applications",
  "business architecture",
  "c programming language",
  "end user support",
  "db",
  "ospf",
  "canvas",
  "requirement gathering",
  "oracle apps",
  "restful web api development",
  "business process modeling",
  "mainframe",
  "hana database",
  "manufacturing process",
  "email support",
  "incident",
  "factory",
  "java collections",
  "standard operating procedures",
  "application integration",
  "sap pp",
  "selenium automation",
  "interviewing",
  "user experience design",
  "cfd",
  "international bpo",
  "tpm",
  "object",
  "optimization",
  "linux internals",
  "security services",
  "azure logic apps",
  "intellectual property",
  "sap cpi",
  "software management",
  "cloud migration",
  "directory",
  "reliability engineering",
  "aks",
  "system development",
  "intune",
  "photography",
  "sap abap hana",
  "google cloud platform",
  "mechatronics",
  "iac",
  "project implementation",
  "embedded development",
  "business consulting",
  "sdwan",
  "mfc",
  "power management",
  "link building",
  "data center",
  "c2h",
  "identity management",
  "certified",
  "functions",
  "subject matter expertise",
  "black box testing",
  "risk analysis",
  "mvp",
  "vxworks",
  "openstack",
  "sap crm",
  "aws cloudformation",
  "windows troubleshooting",
  "system support",
  "sd",
  "python developer",
  "security monitoring",
  "salesforce.com",
  "hardware installation",
  "jsf",
  "pi",
  "l1 support",
  "performance monitoring",
  "bash scripting",
  "data manipulation",
  "technology architecture",
  "underwriting",
  "penetration",
  "international clients",
  "it audit",
  "solarwinds",
  "database management system",
  "analyst",
  "palo alto firewall",
  "back office processing",
  "sqa",
  "artifactory",
  "iaas",
  "workday hcm",
  "sheet metal",
  "project documentation",
  "customer acquisition",
  "vapt",
  "vice president",
  "market intelligence",
  "cloud storage",
  "sap project management",
  "microsoft excel",
  "teamcenter",
  "web applications",
  "data cleansing",
  "powerpoint",
  "sat",
  "groovy",
  "support",
  "sosl",
  "senior management",
  "qlikview",
  "vb script",
  "mac",
  "webapi",
  "web testing",
  "responsive design",
  "product sales",
  "clinical research",
  "leadership training",
  "chatbot",
  "engineering projects",
  "devops tools",
  "microstrategy",
  "development life cycle",
  "containerization",
  "backup",
  "sonarqube",
  "client relationship management",
  "websocket",
  "skill development",
  "it risk management",
  "collections",
  "ec2",
  "sap hcm",
  "test automation framework",
  "service excellence",
  "html and css",
  "cloudera",
  "postgres database",
  "career counselling",
  "information retrieval",
  "btech",
  "spring boot framework",
  "ssh",
  "abap dictionary",
  "product strategy",
  "creative designing",
  "negotiation",
  "angular framework",
  "core banking",
  "workflow analysis",
  "data engineer",
  "datadog",
  "acquisition",
  "new relic",
  "physical verification",
  "npm",
  "mssql",
  "circuit",
  "tracking",
  "project sales",
  "aviation",
  "google adwords",
  "application deployment",
  "layout design",
  "cost reduction",
  "reliability",
  "opencv",
  "search engine optimization",
  "uds",
  "s",
  "objective-c",
  "field",
  "ui testing",
  "financial statements",
  "bss",
  ".net developer",
  "restfull api",
  "revit",
  "ba",
  "x86",
  "epc",
  "target achievement",
  "bca",
  "direct sales",
  "cicd",
  "router",
  "babel",
  "mainframe production support",
  "mocha",
  "rac",
  "bios",
  "ceh",
  "itam",
  "lightning components",
  "incident response",
  "sales operations",
  "application management",
  "business requirement analysis",
  "computer architecture",
  "technology leadership",
  "solid principles",
  "server support",
  "bug fixing",
  "azure cloud services",
  "windows administration",
  "data streaming",
  "business planning",
  "team development",
  "power apps",
  "signal processing",
  "web ui",
  "ccie",
  "dashboards",
  "capital market",
  "netsuite",
  "pam",
  "ms office outlook",
  "salesforce marketing cloud",
  "cqrs",
  "it projects",
  "hris",
  "oscommerce",
  "itil process",
  "ms access",
  "fscm",
  "backbone.js",
  "interface builder",
  "specification",
  "sales strategy",
  "adobe analytics",
  "wordpress themes",
  "data extraction",
  "data conversion",
  "direct",
  "timing closure",
  "android developer",
  "product service",
  "uart",
  "customer handling",
  "codeigniter framework",
  "sow",
  "dax",
  "algorithm development",
  "materials",
  "qnx",
  "routing and switching",
  "salesforce cpq",
  "experience",
  "labview",
  "rtl design",
  "microservices development",
  "rail",
  "cc",
  "model n",
  "customer retention",
  "fi",
  "sketch",
  "spring cloud",
  "patching",
  "sap btp",
  "murex",
  "routing protocols",
  "voice",
  "advanced excel",
  "servicenow itsm",
  "netapp",
  "html css",
  "software product development",
  "director",
  "it sales",
  "searching",
  "nat",
  "hyper-v",
  "civil",
  "switchgear",
  "woocommerce",
  "invoice processing",
  "alm",
  "data entry operation",
  "dms",
  "inbound",
  "operating",
  "oil",
  "log analysis",
  "senior executive",
  "technical management",
  "citrix",
  "juniper",
  "rexx",
  "blockchain",
  "angular developer",
  "tailwind css",
  "jasmine",
  "rs232",
  "ips",
  "service improvement",
  "software development manager",
  "b2c",
  "rest api design",
  "development methodologies",
  "dlp",
  "open",
  "manager internal audit",
  "portfolio management",
  "emr",
  "odata services",
  "microsoft dynamics ax",
  "npd",
  "object-oriented programming",
  "bapis",
  "epm",
  "finacle",
  "user stories",
  "reporting tools",
  "quality systems",
  "downstream",
  "business management",
  "mixed signal",
  "cds views",
  "chip design",
  "user management",
  "spfx",
  "assessment",
  "network programming",
  "regulatory compliance",
  "vba",
  "power apps development",
  "software engineer iii",
  "associate vice president",
  "azure paas",
  "bapi",
  "java web services",
  "db administration",
  "angular material",
  "technical helpdesk",
  "content",
  "crystal report",
  "people management skills",
  "cisco routers",
  "sales executive activities",
  "xamarin",
  "cctv",
  "payment systems",
  "pega development",
  "xsd",
  "dot net core",
  "adobe experience management",
  "center",
  "video conferencing",
  "ites",
  "ale",
  "gateways",
  "ssi",
  "sub",
  "performance analysis",
  "mm",
  "plsql development",
  "site",
  "kvm",
  "enterprise integration",
  "embedded c++",
  "mqtt",
  "hr generalist activities",
  "production engineering",
  "prpc",
  "hybrid apps",
  "osgi",
  "hr processes",
  "3g",
  "business operations",
  "oracle erp",
  "csm",
  "stack development",
  "oracle rac",
  "advanced java",
  "metadata management",
  "financial markets",
  "sql dba",
  "csa",
  "client servicing",
  "expresjs",
  "system maintenance",
  "execution",
  "user support",
  "trading",
  "bugzilla",
  "php programming",
  "jsp servlets",
  "helm",
  "trello",
  "document management",
  "client handling",
  "gradle",
  "network monitoring",
  "advanced analytics",
  "hooks",
  "big data technologies",
  "sap co",
  "desktop troubleshooting",
  "embedded firmware",
  "english typing",
  "desktop administration",
  "servlets",
  "interpersonal",
  "data lake",
  "load",
  "appdynamics",
  "service now",
  "service catalog",
  "autosys",
  "ms sql server",
  "international voice",
  "checkpoint",
  "idocs",
  "it staffing",
  "software asset management",
  "kibana",
  "production planning",
];

const ALLOWED_IPS = [
  "52.66.101.190",
  "3.109.102.144",
  "3.111.60.173",
  "18.60.134.245",
  "18.60.183.142",
];

const PRIORITY_LEVELS: PriorityType[] = ["High", "Medium", "Low"];

const COMPANY_TYPES: CompanyType[] = [
  "Startup",
  "MidSize",
  "MNC",
  "FAANG",
  "GOOGLE",
  "MICROSOFT",
  "META",
  "AMAZON",
  "AIRBNB",
  "UBER",
];

const GOAL_TYPES: GoalType[] = ["3Months", "6Months", "1Year"];

const SUBSCRIPTION_TYPES: SubscriptionType[] = [
  "3Months",
  "5Months",
  "Lifetime",
];

const SUBSCRIPTION_STATUS: SubscriptionStatus[] = [
  "Active",
  "Expired",
  "Trial",
  "Cancelled",
];

const INTERVIEW_CATEGORIES: InterviewCategoryType[] = [
  "MNC",
  "MERN",
  "CollegePlacement",
  "DSA",
  "SystemDesign",
  "GeneralTech",
];

const SUBSCRIPTION_FEATURES: SubscriptionFeature[] = [
  "InterviewQuestions",
  "SystemDesignResources",
  "DSAResources",
  "ResumeWorkshop",
  "JobApplicationWorkshop",
  "ColdEmailAutomation",
  "LinkedInAutomation",
];

const planTypeMap = {
  "1months": { type: "3Months", duration: 1 },
  "3months": { type: "5Months", duration: 3 },
  "6months": { type: "5Months", duration: 6 },
  lifetime: { type: "Lifetime", duration: 999 },
};

enum LeaderboardEnum {
  DAILY = "DAILY",
  WEEKLY = "WEEKLY",
  MONTHLY = "MONTHLY",
}

const POINTS_RULES: Record<UserPointsActionType, number> = {
  ENROLL_COURSE: 50,
  ENROLL_SHEET: 50,
  ENROLL_PROJECT: 50,
  COMPLETE_COURSE_CHAPTER: 20,
  COMPLETE_PROJECT_CHAPTER: 30,
  COMPLETE_COURSE_CERTIFICATE: 50,
  COMPLETE_PROJECT: 100,
  COMPLETE_INTERVIEW_SHEET: 80,
  COMPLETE_QUESTION: 10,
  PROFILE_COMPLETION: 30,
  SOCIAL_SHARE: 15,
  FEEDBACK_SUBMIT: 10,
  VIDEO_WATCH_COMPLETE: 5,
  FIRST_LOGIN: 25,
  DAILY_VISIT: 5,
  STREAK: 3,
  REFER: 20,
  WEBINAR_ATTEND: 40,
  DOWNLOAD_CERTIFICATE: 20,
  HELP_COMMUNITY: 15,
  RECRUITER_ADDED: 25,
  PREPLOG_CREATED: 15,
  PREPLOG_STREAK_3: 25,
  PREPLOG_STREAK_7: 50,
  PREPLOG_STREAK_15: 100,
  PREPLOG_STREAK_30: 200,
  COMPLETE_QUIZ: 30,
  QUIZ_PERFECT_SCORE: 50,
  QUIZ_STREAK: 20,
};

const LEADERBOARD_TYPES: LeaderboardType[] = ["DAILY", "WEEKLY", "MONTHLY"];

const APTITUDE_CATEGORIES: AptitudeCategoryType[] = [
  "QUANTITATIVE",
  "VERBAL",
  "REASONING",
  "INTERVIEW",
];

const APTITUDE_SUB_CATEGORIES: AptitudeSubCategoryType[] = [
  "ARITHMETIC_APTITUDE",
  "DATA_INTERPRETATION",
  "VERBAL_ABILITY",
  "LOGICAL_REASONING",
  "GD_ROUND",
  "HR_INTERVIEW",
];

const APTITUDE_ANSWER_FORMATS: AptitudeAnswerFormatType[] = [
  "SPEED",
  "RULES",
  "PERSPECTIVE",
  "BEHAVIORAL",
];

const APTITUDE_SUB_CATEGORY_FORMAT_MAP: Record<
  AptitudeSubCategoryType,
  AptitudeAnswerFormatType
> = {
  ARITHMETIC_APTITUDE: "SPEED",
  DATA_INTERPRETATION: "SPEED",
  VERBAL_ABILITY: "RULES",
  LOGICAL_REASONING: "SPEED",
  GD_ROUND: "PERSPECTIVE",
  HR_INTERVIEW: "BEHAVIORAL",
};

// Pre-defined aptitude topics: the shared source of truth between TBE-Web and Agents.
// When adding a new topic, update BOTH this list and the Agents' TOPIC_REGISTRY.
const APTITUDE_TOPICS: AptitudeTopicDefinition[] = [
  // ─── Quantitative > Arithmetic Aptitude ───────────────────────────────
  {
    name: "Problem on Trains",
    slug: "problem-on-trains",
    category: "QUANTITATIVE",
    subCategory: "ARITHMETIC_APTITUDE",
  },
  {
    name: "Time and Distance",
    slug: "time-and-distance",
    category: "QUANTITATIVE",
    subCategory: "ARITHMETIC_APTITUDE",
  },
  {
    name: "Height and Distance",
    slug: "height-and-distance",
    category: "QUANTITATIVE",
    subCategory: "ARITHMETIC_APTITUDE",
  },
  {
    name: "Time and Work",
    slug: "time-and-work",
    category: "QUANTITATIVE",
    subCategory: "ARITHMETIC_APTITUDE",
  },
  {
    name: "Simple Interest",
    slug: "simple-interest",
    category: "QUANTITATIVE",
    subCategory: "ARITHMETIC_APTITUDE",
  },
  {
    name: "Compound Interest",
    slug: "compound-interest",
    category: "QUANTITATIVE",
    subCategory: "ARITHMETIC_APTITUDE",
  },
  {
    name: "Profit and Loss",
    slug: "profit-and-loss",
    category: "QUANTITATIVE",
    subCategory: "ARITHMETIC_APTITUDE",
  },
  {
    name: "Partnership",
    slug: "partnership",
    category: "QUANTITATIVE",
    subCategory: "ARITHMETIC_APTITUDE",
  },
  {
    name: "Percentage",
    slug: "percentage",
    category: "QUANTITATIVE",
    subCategory: "ARITHMETIC_APTITUDE",
  },
  {
    name: "Calendar",
    slug: "calendar",
    category: "QUANTITATIVE",
    subCategory: "ARITHMETIC_APTITUDE",
  },
  {
    name: "Probability",
    slug: "probability",
    category: "QUANTITATIVE",
    subCategory: "ARITHMETIC_APTITUDE",
  },
  {
    name: "Clocks",
    slug: "clocks",
    category: "QUANTITATIVE",
    subCategory: "ARITHMETIC_APTITUDE",
  },
  {
    name: "Average",
    slug: "average",
    category: "QUANTITATIVE",
    subCategory: "ARITHMETIC_APTITUDE",
  },
  {
    name: "Area",
    slug: "area",
    category: "QUANTITATIVE",
    subCategory: "ARITHMETIC_APTITUDE",
  },
  {
    name: "Volume and Surface Areas",
    slug: "volume-and-surface-areas",
    category: "QUANTITATIVE",
    subCategory: "ARITHMETIC_APTITUDE",
  },
  {
    name: "Ratio",
    slug: "ratio",
    category: "QUANTITATIVE",
    subCategory: "ARITHMETIC_APTITUDE",
  },
  {
    name: "Proportion",
    slug: "proportion",
    category: "QUANTITATIVE",
    subCategory: "ARITHMETIC_APTITUDE",
  },
  {
    name: "Surds and Indices",
    slug: "surds-and-indices",
    category: "QUANTITATIVE",
    subCategory: "ARITHMETIC_APTITUDE",
  },
  {
    name: "Pipes and Cisterns",
    slug: "pipes-and-cisterns",
    category: "QUANTITATIVE",
    subCategory: "ARITHMETIC_APTITUDE",
  },
  {
    name: "Races and Games",
    slug: "races-and-games",
    category: "QUANTITATIVE",
    subCategory: "ARITHMETIC_APTITUDE",
  },
  {
    name: "Logarithms",
    slug: "logarithms",
    category: "QUANTITATIVE",
    subCategory: "ARITHMETIC_APTITUDE",
  },
  {
    name: "Stocks and Shares",
    slug: "stocks-and-shares",
    category: "QUANTITATIVE",
    subCategory: "ARITHMETIC_APTITUDE",
  },
  {
    name: "Simplification",
    slug: "simplification",
    category: "QUANTITATIVE",
    subCategory: "ARITHMETIC_APTITUDE",
  },
  {
    name: "HCF and LCM",
    slug: "hcf-and-lcm",
    category: "QUANTITATIVE",
    subCategory: "ARITHMETIC_APTITUDE",
  },

  // ─── Quantitative > Data Interpretation ───────────────────────────────
  {
    name: "Table Charts",
    slug: "table-charts",
    category: "QUANTITATIVE",
    subCategory: "DATA_INTERPRETATION",
  },
  {
    name: "Bar Charts",
    slug: "bar-charts",
    category: "QUANTITATIVE",
    subCategory: "DATA_INTERPRETATION",
  },
  {
    name: "Pie Charts",
    slug: "pie-charts",
    category: "QUANTITATIVE",
    subCategory: "DATA_INTERPRETATION",
  },
  {
    name: "Line Charts",
    slug: "line-charts",
    category: "QUANTITATIVE",
    subCategory: "DATA_INTERPRETATION",
  },

  // ─── Verbal > Verbal Ability ──────────────────────────────────────────
  {
    name: "Spotting Errors",
    slug: "spotting-errors",
    category: "VERBAL",
    subCategory: "VERBAL_ABILITY",
  },
  {
    name: "Synonyms",
    slug: "synonyms",
    category: "VERBAL",
    subCategory: "VERBAL_ABILITY",
  },
  {
    name: "Antonyms",
    slug: "antonyms",
    category: "VERBAL",
    subCategory: "VERBAL_ABILITY",
  },

  // ─── Reasoning > Logical Reasoning ────────────────────────────────────
  {
    name: "Number Series",
    slug: "number-series",
    category: "REASONING",
    subCategory: "LOGICAL_REASONING",
  },
  {
    name: "Letter and Symbol Series",
    slug: "letter-and-symbol-series",
    category: "REASONING",
    subCategory: "LOGICAL_REASONING",
  },
  {
    name: "Verbal Classification",
    slug: "verbal-classification",
    category: "REASONING",
    subCategory: "LOGICAL_REASONING",
  },
  {
    name: "Analogies",
    slug: "analogies",
    category: "REASONING",
    subCategory: "LOGICAL_REASONING",
  },
  {
    name: "Matching Definition",
    slug: "matching-definition",
    category: "REASONING",
    subCategory: "LOGICAL_REASONING",
  },
  {
    name: "Logical Games",
    slug: "logical-games",
    category: "REASONING",
    subCategory: "LOGICAL_REASONING",
  },
  {
    name: "Cause and Effect",
    slug: "cause-and-effect",
    category: "REASONING",
    subCategory: "LOGICAL_REASONING",
  },
  {
    name: "Statement and Assumption",
    slug: "statement-and-assumption",
    category: "REASONING",
    subCategory: "LOGICAL_REASONING",
  },
  {
    name: "Logical Distance",
    slug: "logical-distance",
    category: "REASONING",
    subCategory: "LOGICAL_REASONING",
  },
  {
    name: "Deduction",
    slug: "deduction",
    category: "REASONING",
    subCategory: "LOGICAL_REASONING",
  },
  {
    name: "Theme Detection",
    slug: "theme-detection",
    category: "REASONING",
    subCategory: "LOGICAL_REASONING",
  },
  {
    name: "Analyzing Arguments",
    slug: "analyzing-arguments",
    category: "REASONING",
    subCategory: "LOGICAL_REASONING",
  },
  {
    name: "Logical Problems",
    slug: "logical-problems",
    category: "REASONING",
    subCategory: "LOGICAL_REASONING",
  },
  {
    name: "Making Judgments",
    slug: "making-judgments",
    category: "REASONING",
    subCategory: "LOGICAL_REASONING",
  },

  // ─── Interview > GD Round ─────────────────────────────────────────────
  {
    name: "Politics",
    slug: "politics",
    category: "INTERVIEW",
    subCategory: "GD_ROUND",
  },
  {
    name: "Economics",
    slug: "economics",
    category: "INTERVIEW",
    subCategory: "GD_ROUND",
  },
  {
    name: "Social Issues",
    slug: "social-issues",
    category: "INTERVIEW",
    subCategory: "GD_ROUND",
  },
  {
    name: "Technology",
    slug: "technology",
    category: "INTERVIEW",
    subCategory: "GD_ROUND",
  },
  {
    name: "General Topics",
    slug: "general-topics",
    category: "INTERVIEW",
    subCategory: "GD_ROUND",
  },

  // ─── Interview > HR Interview ─────────────────────────────────────────
  {
    name: "Self Introduction",
    slug: "self-introduction",
    category: "INTERVIEW",
    subCategory: "HR_INTERVIEW",
  },
  {
    name: "Career Goals",
    slug: "career-goals",
    category: "INTERVIEW",
    subCategory: "HR_INTERVIEW",
  },
  {
    name: "Work Experience",
    slug: "work-experience",
    category: "INTERVIEW",
    subCategory: "HR_INTERVIEW",
  },
  {
    name: "Behavioral Questions",
    slug: "behavioral-questions",
    category: "INTERVIEW",
    subCategory: "HR_INTERVIEW",
  },
  {
    name: "Strengths and Weaknesses",
    slug: "strengths-and-weaknesses",
    category: "INTERVIEW",
    subCategory: "HR_INTERVIEW",
  },
  {
    name: "General HR Questions",
    slug: "general-hr-questions",
    category: "INTERVIEW",
    subCategory: "HR_INTERVIEW",
  },
];

const APTITUDE_TOPIC_SLUGS: string[] = APTITUDE_TOPICS.map((t) => t.slug);

const DSA_DOMAIN: DSADomainType[] = [
  "FRONTEND",
  "BACKEND",
  "GENERAL",
  "FULLSTACK",
  "DSA",
];

const DSA_DIFFICULTY: DSADifficultyType[] = ["EASY", "MEDIUM", "HARD"];

/** Sheet order, Mongo `$indexOfArray`, and validation — single source of truth. */
const DSA_TOPICS: DSATopicType[] = [
  "ARRAY",
<<<<<<< HEAD
  "STRING",
=======
>>>>>>> c4aadea2 (feat(dsa): seed graph and queue content, stabilization, and topic cleanup)
  "HASHMAP",
  "SLIDING_WINDOW",
  "PREFIX_SUM",
  "SORTING",
  "BINARY_SEARCH",
  "MATH",
  "BIT_MANIPULATION",
  "RECURSION",
  "LINKED_LIST",
  "STACK",
  "QUEUE",
  "BINARY_TREE",
  "TREE",
  "BST",
  "HEAP",
  "TRIE",
  "GRAPH",
  "BACKTRACKING",
  "DYNAMIC_PROGRAMMING",
  "GREEDY",
<<<<<<< HEAD
  "UNION_FIND",
  "SIMULATION",
  "DESIGN",
=======
  "STRING",
  "MATH",
  "TRIE",
  "HEAP",
  "UNION_FIND",
  "RECURSION",
>>>>>>> c4aadea2 (feat(dsa): seed graph and queue content, stabilization, and topic cleanup)
  "MONOTONIC_STACK",
];

export {
  ALLOWED_IPS,
  APTITUDE_ANSWER_FORMATS,
  APTITUDE_CATEGORIES,
  APTITUDE_SUB_CATEGORIES,
  APTITUDE_SUB_CATEGORY_FORMAT_MAP,
  APTITUDE_TOPIC_SLUGS,
  APTITUDE_TOPICS,
  CERTIFICATE_TYPE,
  COMPANY_TYPES,
  DIFFICULTY_LEVEL,
  DSA_DIFFICULTY,
  DSA_DOMAIN,
  DSA_TOPICS,
  GOAL_TYPES,
  INTERVIEW_CATEGORIES,
  INTERVIEW_QUESTION_FREQUENCY,
  JOB_DOMAIN_MAPPER,
  JOB_DOMAIN_NORMALIZER,
  JOB_LOCATION_NORMALIZER,
  JOB_SKILL_NORMALIZER,
  LEADERBOARD_TYPES,
  LeaderboardEnum,
  NOTIFICATION_TYPE,
  planTypeMap,
  PLATFORM_USAGE,
  POINTS_RULES,
  PRIORITY_LEVELS,
  PROJECT_SKILLS,
  ROADMAPS,
  SKILL_BLACKLIST,
  SUBSCRIPTION_FEATURES,
  SUBSCRIPTION_STATUS,
  SUBSCRIPTION_TYPES,
  USER_POINTS_ACTION,
  USER_ROLE,
  WORK_DOMAIN,
  YOUTUBE_API_PATH,
};
